{
 "title": "Block height monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain_name",
    "label": "Chain",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"chain\",\n    predicate: (r) => true,\n    start: -1d\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Block height difference",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "Chains = from(bucket: \"blockheights\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"block_height_request\")\n  |> filter(fn: (r) => r.chain == \"${chain_name}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"block_height\")\n  |> group(columns: [\"url\"])\n  |> truncateTimeColumn(unit: 1s)\n  |> drop(columns: [\"_field\", \"_measurement\", \"api\", \"chain\"])\n  |> yield(name: \"Chains\")"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"blockheights\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"block_height_request\")\n  |> filter(fn: (r) => r.chain == \"${chain_name}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"block_height\")\n  |> drop(columns: [\"_field\", \"_measurement\", \"api\", \"chain\"])\n  |> map(fn: (r) => ({r with url: strings.trimPrefix(v: r.url, prefix: \"http://\")}))\n  |> map(fn: (r) => ({r with url: strings.trimPrefix(v: r.url, prefix: \"https://\")}))\n  |> map(fn: (r) => ({r with url: strings.trimPrefix(v: r.url, prefix: \"wss://\")}))"
    }
   ]
  },
  {
   "title": "Maximum latency",
   "type": "gauge",
   "gridPos": { "h": 18, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\n\nChains = from(bucket: \"blockheights\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"block_height_request\")\n  |> filter(fn: (r) => r.chain == \"${chain_name}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_total\")\n  |> group(columns: [\"url\"])\n  |> truncateTimeColumn(unit: 1s)\n  |> drop(columns: [\"_field\", \"_measurement\", \"api\", \"chain\"])\n  |> map(fn: (r) => ({r with url: strings.trimPrefix(v: r.url, prefix: \"http://\")}))\n  |> map(fn: (r) => ({r with url: strings.trimPrefix(v: r.url, prefix: \"https://\")}))\n  |> map(fn: (r) => ({r with url: strings.trimPrefix(v: r.url, prefix: \"wss://\")}))\n  |> yield(name: \"Chains\")"
    }
   ]
  },
  {
   "title": "Max block difference in time period",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "Chains = from(bucket: \"blockheights\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"block_height_request\")\n  |> filter(fn: (r) => r.chain == \"${chain_name}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"block_height\")\n  |> group(columns: [\"url\"])\n  |> truncateTimeColumn(unit: 1s)\n  |> drop(columns: [\"_field\", \"_measurement\", \"api\", \"chain\"])\n  |> yield(name: \"Chains\")"
    }
   ]
  },
  {
   "title": "Latency (RPC request time_total)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 8, "y": 9 },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"blockheights\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"block_height_request\")\n  |> filter(fn: (r) => r.chain == \"${chain_name}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_total\")\n  |> drop(columns: [\"_field\", \"_measurement\", \"api\", \"chain\"])\n  |> map(fn: (r) => ({r with url: strings.trimPrefix(v: r.url, prefix: \"http://\")}))\n  |> map(fn: (r) => ({r with url: strings.trimPrefix(v: r.url, prefix: \"https://\")}))\n  |> map(fn: (r) => ({r with url: strings.trimPrefix(v: r.url, prefix: \"wss://\")}))"
    }
   ]
  }
 ]
}